name: Metrics
on:
  schedule: [{cron: "0 */12 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate Subtle Minimalist Metrics Card
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics.svg

          # Layout Configuration
          user: mani-hash
          template: classic
          base: header
          config_timezone: Asia/Colombo

          theme: tokyonight
          config_padding: 0, 10
          config_order: base.header
          
          include_all_commits: true
          count_private: true

          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
          plugin_languages_limit: 6
          
          plugin_languages_indepth: yes
          
          # Ignore heavy boilerplate formats entirely
          plugin_languages_skipped: tex, markdown, html, css, blade, hack